package net.jtownson.xdfbinext.bace.DME861_R1C9J8B3B

import net.jtownson.xdfbinext.a2l.{CurveType, MapType}
import net.jtownson.xdfbinext.bace.BaceDSL.MeasurementType.OutMeasurement

object Tch_039_004_0 {

  def BMW_MOD_TchAd_100ms(
      BMWtchad_fac_Raw_uw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchbas_rat_p_BascBefCmpr_uw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchctr_b_IpRst2_bo: BigDecimal,
      BMWtchctr_b_IpRst_bo: BigDecimal,
      BMWtchctr_b_IpStop2_bo: BigDecimal,
      BMWtchctr_b_IpStop_bo: BigDecimal,
      BMWtchctr_fac_FadeAdp_ub: BigDecimal,
      BMWtchctr_fac_Ip_uw: BigDecimal,
      BMWtchctr_pct_WgCrtd3_uw: BigDecimal,
      BMWtchctr_pct_WgIp_sw: BigDecimal,
      BMWtchdiag_b_AdpOff_bo: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      BMWtchtbc_fac_EngHot_ub: BigDecimal,
      BMWtchtbc_t_BefCmprMnfAvg_sw: BigDecimal,
      Nkw: BigDecimal,
      Tans: BigDecimal,
      Tmot: BigDecimal,
      BMWtchad_fac_EngHotMin_C: BigDecimal,
      BMWtchad_fac_IpMax_C: BigDecimal,
      BMWtchad_fac_IpMin_C: BigDecimal,
      BMWtchad_fac_IpOfs_C: BigDecimal,
      BMWtchad_fac_Ip_C: BigDecimal,
      BMWtchad_fac_PBasc_T: CurveType[BigDecimal, BigDecimal],
      BMWtchad_fac_p_CmprLimMax_C: BigDecimal,
      BMWtchad_n_EngMax_C: BigDecimal,
      BMWtchad_n_EngMin_C: BigDecimal,
      BMWtchad_n_Eng_Ca: Array[BigDecimal],
      BMWtchad_p_DifAbsMax_C: BigDecimal,
      BMWtchad_p_ReqDynMax_C: BigDecimal,
      BMWtchad_p_ReqDynMin_C: BigDecimal,
      BMWtchad_pct_WgIpAdpToDwn_C: BigDecimal,
      BMWtchad_pct_WgIpAdpToUp_C: BigDecimal,
      BMWtchad_swi_AcvMan_C: String,
      BMWtchad_t_EngMin_C: BigDecimal,
      BMWtchad_t_MnfMax_C: BigDecimal,
      BMWtchad_ti_DlyAftIpIni_C: BigDecimal,
      BMWtchctr_fac_FadeAdpMin_C: BigDecimal,
      BMWtchad_swi_Rst_C: String,
      BMWtchctr_swi_IpPwrAcvn_C: String,
      BMWtchad_fac_AdpAry_sl: OutMeasurement[BigDecimal],
      BMWtchad_fac_AdpAry_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchAd_10ms(
      BMWtchad_fac_AdpAry_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      Nkw: BigDecimal,
      BMWtchad_fac_AdpCrtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchad_n_Eng_Ca: Array[BigDecimal],
      BMWtchad_fac_Raw_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchAd_swini(
      BMWeng_b_EcuPwsFaild_bo: BigDecimal,
      BMWtchad_fac_AdpAry_sl: BigDecimal,
      BMWtchad_fac_AdpAry_uw: BigDecimal,
      BMWtchad_swi_Rst_C: String
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBas_Misc_10ms(
      BMWbdy_b_CluOp10_bo: BigDecimal,
      BMWbdy_b_EgFlp_bo: BigDecimal,
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWtchbas_rat_p_BefThrAmb_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_Req_bo: BigDecimal,
      BMWtqe_b_DfcoFas_bo: BigDecimal,
      BMWtqe_b_Dfco_bo: BigDecimal,
      BMWtqe_b_Noise_bo: BigDecimal,
      BMWveh_b_TranDrp_bo: BigDecimal,
      Msakzu: BigDecimal,
      Nkw: BigDecimal,
      Nstat: BigDecimal,
      Pwg_ist: BigDecimal,
      St_ba_agf: BigDecimal,
      St_ba_agf_B_kath_korr: BigDecimal,
      St_bls: BigDecimal,
      St_bls_B_bls: BigDecimal,
      St_ngang0: BigDecimal,
      St_ngang0_B_gangnull: BigDecimal,
      St_ngang0_B_gangnullerw: BigDecimal,
      St_ngang0_B_ngangdok: BigDecimal,
      St_ngang0_B_nggelernt: BigDecimal,
      St_ngang0_B_ngimlf: BigDecimal,
      St_ngang0_B_nglernakt: BigDecimal,
      St_progression: BigDecimal,
      St_progression_B_eco: BigDecimal,
      St_progression_B_sport: BigDecimal,
      V: BigDecimal,
      V_rad: BigDecimal,
      Var_at: BigDecimal,
      Var_dkg: BigDecimal,
      Var_hs: BigDecimal,
      BMWtchbas_cw_Noise_C: BigDecimal,
      BMWtchbas_fac_n_FilDyn_C: BigDecimal,
      BMWtchbas_mf_NoiseMin_C: BigDecimal,
      BMWtchbas_n_FlGcMin_C: BigDecimal,
      BMWtchbas_n_NoiseMin_C: BigDecimal,
      BMWtchbas_n_OfsNoiseOff_C: BigDecimal,
      BMWtchbas_nr_n_AvgDyn2_C: BigDecimal,
      BMWtchbas_pct_AccrFlGcMin_C: BigDecimal,
      BMWtchbas_pct_AccrFlGcMin_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_pct_AccrGraFlGcMax_C: BigDecimal,
      BMWtchbas_pct_AccrGradNoiseMin_C: BigDecimal,
      BMWtchbas_pct_AccrNoiseMin_C: BigDecimal,
      BMWtchbas_rat_p_BefThrFlGc_C: BigDecimal,
      BMWtchbas_ti_DlyAccr0FlGcDi_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcCluDi_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcEna_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcHld_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcLock_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcMax_C: BigDecimal,
      BMWtchbas_ti_DlyFlGcPucDi_C: BigDecimal,
      BMWtchbas_ti_DlyNoiseOff_C: BigDecimal,
      BMWtchbas_b_FlGcHld_bo: OutMeasurement[BigDecimal],
      BMWtchbas_b_FlGc_bo: OutMeasurement[BigDecimal],
      BMWtchbas_b_Noise_bo: OutMeasurement[BigDecimal],
      BMWtchbas_n_Dyn_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBas_P_10ms(
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_st_Opm_ub: BigDecimal,
      BMWtchsp_p_Req_uw: BigDecimal,
      BMWtchsp_volf_BefTc_uw: BigDecimal,
      BMWtchtbc_t_BefCmpr_sw: BigDecimal,
      Nkw: BigDecimal,
      Pumg: BigDecimal,
      BMWtchbas_fac_FilPBefThrDyn_C: BigDecimal,
      BMWtchbas_fac_FilPDifCrtn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_fac_FilPDif_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_fac_TcBascCrtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbas_nr_PDifGraAvg_C: BigDecimal,
      BMWtchbas_p_DifAmbBefCmpr_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_rat_p_TcBascCond_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_rat_p_TcBascEco_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_rat_p_TcBascRoofOp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_rat_p_TcBascSpt_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_rat_p_TcBasc_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbas_p_BefCmpr_uw: OutMeasurement[BigDecimal],
      BMWtchbas_p_BefThrDyn_sw: OutMeasurement[BigDecimal],
      BMWtchbas_p_DifGraRaw_sw: OutMeasurement[BigDecimal],
      BMWtchbas_p_DifGra_sw: OutMeasurement[BigDecimal],
      BMWtchbas_p_Dif_sw: OutMeasurement[BigDecimal],
      BMWtchbas_p_TcBasc_uw: OutMeasurement[BigDecimal],
      BMWtchbas_rat_p_BascBefCmpr_uw: OutMeasurement[BigDecimal],
      BMWtchbas_rat_p_BefCmpr_uw: OutMeasurement[BigDecimal],
      BMWtchbas_rat_p_BefThrAmb_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBas_Race_10ms(
      BMWosc_acvn_ModEng_ub: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      Pwg_ist: BigDecimal,
      St_bls: BigDecimal,
      St_bls_B_bls: BigDecimal,
      St_mdanfahr_cc: BigDecimal,
      St_mdanfahr_cc_B_anfahr_nmax_disp_flag: BigDecimal,
      St_mdanfahr_cc_B_rennstart_aktiv: BigDecimal,
      St_rsta_mdkg: BigDecimal,
      Var_at: BigDecimal,
      Var_dkg: BigDecimal,
      BMWtchbas_acvn_ModEngRaceStrt_C: BigDecimal,
      BMWtchbas_cw_RaceStr_C: BigDecimal,
      BMWtchbas_pct_AccrRaceStrtDly_C: BigDecimal,
      BMWtchbas_pct_AccrRaceStrt_C: BigDecimal,
      BMWtchbas_swi_RaceVarSel_C: String,
      BMWtchbas_ti_DlyRaceStr_C: BigDecimal,
      BMWtchbas_b_RaceStr_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBov_Acv_10ms(
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWtchbas_b_FlGcHld_bo: BigDecimal,
      BMWtchbas_p_DifGraRaw_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec2_bo: BigDecimal,
      BMWtchsp_b_RfLimAcv_bo: BigDecimal,
      Drf_soll: BigDecimal,
      F_psspu: BigDecimal,
      Nkw: BigDecimal,
      Pbremsu: BigDecimal,
      St_bgkuppl1: BigDecimal,
      St_bgkuppl1_B_ll: BigDecimal,
      St_dsc_can: BigDecimal,
      Status_usecase_antr: BigDecimal,
      V_can: BigDecimal,
      BMWtchbov_b_AcvnMan_C: String,
      BMWtchbov_cw_1_C: BigDecimal,
      BMWtchbov_cw_DscSpt_C: BigDecimal,
      BMWtchbov_n_AcvnMax_C: BigDecimal,
      BMWtchbov_n_DiSpt_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbov_n_Di_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbov_n_OfsAcvMin_C: BigDecimal,
      BMWtchbov_nr_PDifPrdn_C: BigDecimal,
      BMWtchbov_p_BrkMaxDi_C: BigDecimal,
      BMWtchbov_p_DifAcvnSpt_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_p_DifAcvn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_p_DifDeac_C: BigDecimal,
      BMWtchbov_rat_FiGraAcvn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbov_rat_FiGraDeac_C: BigDecimal,
      BMWtchbov_rat_p_InAmbSpt_C: BigDecimal,
      BMWtchbov_rat_p_InAmb_C: BigDecimal,
      BMWtchbov_st_Map_Ca: Array[String],
      BMWtchbov_swi_Man_C: String,
      BMWtchbov_ti_AcvnMax_C: BigDecimal,
      BMWtchbov_ti_AftStrtEndEna_C: BigDecimal,
      BMWtchbov_ti_DlyFiGraAcvn_C: BigDecimal,
      BMWtchbov_ti_Lock_C: BigDecimal,
      BMWtchbov_v_VehMaxDi_C: BigDecimal,
      BMWtchbov_b_Acv_bo: OutMeasurement[BigDecimal],
      BMWtchbov_st_Opm_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBov_Mf_10ms(
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWosc_fac_DfcoDrvgSit_ub: BigDecimal,
      BMWtchbas_p_BefCmpr_uw: BigDecimal,
      BMWtchbov_b_Acv_bo: BigDecimal,
      BMWtchbov_st_Opm_ub: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchsp_p_DifIco_uw: BigDecimal,
      BMWtqe_b_IgTqAcv_bo: BigDecimal,
      Nkw: BigDecimal,
      St_dps: BigDecimal,
      St_dps_B_gd: BigDecimal,
      V_can: BigDecimal,
      BMWtchbov_cw_CylOffEna_C: BigDecimal,
      BMWtchbov_fac_FadeDec_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbov_fac_mf_ThrEcoMin_C: BigDecimal,
      BMWtchbov_fac_mf_ThrMin_C: BigDecimal,
      BMWtchbov_fac_mf_ThrSptMin_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_fac_mf_ThrThrEcoMin_C: BigDecimal,
      BMWtchbov_fac_mf_ThrThrMin_C: BigDecimal,
      BMWtchbov_fac_mf_ThrThrSptMin_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_fac_mf_VvtEcoMin_C: BigDecimal,
      BMWtchbov_fac_mf_VvtMin_C: BigDecimal,
      BMWtchbov_fac_mf_VvtSptMin_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_mf_PmpLim_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchbov_rat_p_CmprThdVlvOp_C: BigDecimal,
      BMWtchbov_swi_CylOff0Flow_C: String,
      BMWtchbov_swi_TiRmp_C: String,
      BMWtchbov_swi_VlvOpAll_C: String,
      BMWtchbov_ti_HldFlow_T: CurveType[BigDecimal, BigDecimal],
      BMWtchbov_ti_ToutIgTqAcv_C: BigDecimal,
      BMWtchbov_b_CylOffEna_bo: OutMeasurement[BigDecimal],
      BMWtchbov_b_VlvOp_bo: OutMeasurement[BigDecimal],
      BMWtchbov_mf_ThrMin_uw: OutMeasurement[BigDecimal],
      BMWtchbov_mf_VvtMin_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBpi_100ms(
      BMWeisy_b_PSnsrDblErr_bo: BigDecimal,
      BMWeisy_b_PSnsrPreThrErr_bo: BigDecimal,
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWtchbpi_fac_P2Pct_uw: BigDecimal,
      Pumg: BigDecimal,
      St_kl15: BigDecimal,
      St_kl15_B_dc_new: BigDecimal,
      St_kl15_B_kl15_ep: BigDecimal,
      St_kl15_B_kl15_vorab: BigDecimal,
      BMWtchbpi_fac_Lpf_C: BigDecimal,
      BMWtchbpi_p_TcSptDisp_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchBpi_swini(
      BMWtchbpi_p_MaxTcSptDisp_C: BigDecimal,
      BMWtchbpi_fac_P2Pct_uw: OutMeasurement[BigDecimal],
      BMWtchbpi_p_MaxTcSptDisp_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCo_Acv_10ms(
      BMWchas_stb_2_ub: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_DtOpInj2_bc: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_GearAcv_bc: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_Idl_bc: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_Inj2Did_bc: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_Inj2Ena_bc: BigDecimal,
      BMWchas_stb_2_ub_BMWchas_b_Inj3Ena_bc: BigDecimal,
      BMWchc_b_WgOpIdl_bo: BigDecimal,
      BMWchpf_b_OpmTc_bo: BigDecimal,
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWtchbas_b_FlGc_bo: BigDecimal,
      BMWtchbas_b_Noise_bo: BigDecimal,
      BMWtchbas_b_RaceStr_bo: BigDecimal,
      BMWtchbas_p_TcBasc_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_LnkAftCmprSlv_bo: BigDecimal,
      BMWtchdiag_b_CtlrOff_bo: BigDecimal,
      Pld_soll: BigDecimal,
      Pssol: BigDecimal,
      Pumg: BigDecimal,
      BMWtchco_fac_AcvPlOn_C: BigDecimal,
      BMWtchco_fac_FadePl_T: CurveType[BigDecimal, BigDecimal],
      BMWtchco_fac_FilFadePl_C: BigDecimal,
      BMWtchco_p_HysAcv_C: BigDecimal,
      BMWtchco_swi_AcvPl_C: String,
      BMWtchco_swi_ClcCtlr_C: String,
      BMWtchco_swi_ClcPl_C: String,
      BMWtchco_swi_FlGcCtlrOn_C: String,
      BMWtchco_ti_DlyCtlrOff_C: BigDecimal,
      BMWtchsp_swi_PSpRace_C: String,
      BMWtchco_b_AcvPl_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_Acv_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_ClcCtlr_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_ClcPl_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_CthIdl_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_Rdy_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_Req_bo: OutMeasurement[BigDecimal],
      BMWtchco_fac_FadePl_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCo_Opm_10ms(
      BMWeisy_b_PSnsrPreThrPlau_bo: BigDecimal,
      BMWeng_b_CkMovg_bo: BigDecimal,
      BMWls_b_CondRiskIco_bo: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtqe_b_Dfco_bo: BigDecimal,
      Pwg_ist: BigDecimal,
      St_bgkuppl1: BigDecimal,
      St_bgkuppl1_B_ll: BigDecimal,
      St_dsc_can: BigDecimal,
      St_fgr: BigDecimal,
      St_fgr_B_fgr_akt: BigDecimal,
      St_fgr_B_sport_aktiv: BigDecimal,
      St_fw: BigDecimal,
      St_fw_B_hschalt_komb: BigDecimal,
      St_fw_B_ldm_akt04: BigDecimal,
      St_fw_B_ldm_off: BigDecimal,
      St_fw_B_ldm_offhs: BigDecimal,
      St_fw_B_ldm_offreg: BigDecimal,
      St_fw_B_ldm_offrs: BigDecimal,
      St_fw_B_rschalt_komb: BigDecimal,
      St_poscab: BigDecimal,
      Stat_vmbm: BigDecimal,
      Status_usecase_antr: BigDecimal,
      Toel: BigDecimal,
      V_can: BigDecimal,
      BMWtchco_cw_1_C: BigDecimal,
      BMWtchco_cw_DscSpt_C: BigDecimal,
      BMWtchco_cw_RoofOp_C: BigDecimal,
      BMWtchco_rat_AccrEcoOff_C: BigDecimal,
      BMWtchco_rat_AccrSpt_C: BigDecimal,
      BMWtchco_rat_gra_AccrEcoOff_C: BigDecimal,
      BMWtchco_rat_gra_AccrEcoOn_C: BigDecimal,
      BMWtchco_rat_gra_AccrSpt_C: BigDecimal,
      BMWtchco_st_OpmMap_Ca: Array[String],
      BMWtchco_t_OilEco_C: BigDecimal,
      BMWtchco_ti_DlyAccrEcoOn_C: BigDecimal,
      BMWtchco_ti_DlyAccrSpt_C: BigDecimal,
      BMWtchco_v_OpmRoofOpHys_C: BigDecimal,
      BMWtchco_v_OpmRoofOpMax_C: BigDecimal,
      BMWtchco_v_OpmRoofOpMin_C: BigDecimal,
      BMWtchco_v_OpmSptHys_C: BigDecimal,
      BMWtchco_v_OpmSptMax_C: BigDecimal,
      BMWtchco_v_OpmSptMin_C: BigDecimal,
      BMWtchco_st_Opm_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCo_Pam_10ms(
      Tic10ms: BigDecimal,
      BMWtchco_cw_Clc10MilliSe2_C: BigDecimal,
      BMWtchco_cw_Clc10MilliSe_C: BigDecimal,
      BMWtchco_b_Clc10MilliSec2_bo: OutMeasurement[BigDecimal],
      BMWtchco_b_Clc10MilliSec_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCo_swini(BMWtchco_b_LnkAftCmprSlv_bo: OutMeasurement[BigDecimal]): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_100ms(
      Fho: BigDecimal,
      Pak: BigDecimal,
      Tumg: BigDecimal,
      V_can: BigDecimal,
      BMWtchctr_fac_AltiCrtn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_pct_WgAltiCrtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_v_WgClsdPlHys_C: BigDecimal,
      BMWtchctr_v_WgClsdPlMax_C: BigDecimal,
      BMWtchctr_v_WgClsdPlMin_C: BigDecimal,
      BMWtchctr_b_WgClsdPl_bo: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgAltiCrtn_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_PosAdIp_10ms(
      BMWtchad_fac_Raw_uw: BigDecimal,
      BMWtchbas_b_FlGcHld_bo: BigDecimal,
      BMWtchbas_n_Dyn_sw: BigDecimal,
      BMWtchbas_p_BefThrDyn_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchbas_rat_p_BascBefCmpr_uw: BigDecimal,
      BMWtchco_b_AcvPl_bo: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchctr_pct_WgAct_uw: BigDecimal,
      BMWtchctr_pct_WgCrtd1_uw: BigDecimal,
      BMWtchctr_pct_WgCrtd3_uw: BigDecimal,
      BMWtchdiag_b_LimPctl_bo: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      BMWtchsp_rat_p_Cmpr_uw: BigDecimal,
      Nkw: BigDecimal,
      BMWtchctr_fac_FadeAdpMax_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_FadeAdp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_IpPctWg_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_n_DynIpRstMax_C: BigDecimal,
      BMWtchctr_n_DynIpRstMin_C: BigDecimal,
      BMWtchctr_p_BefThrDynIpStop_C: BigDecimal,
      BMWtchctr_p_DifIpRstMax_C: BigDecimal,
      BMWtchctr_p_DifIpRstMin_C: BigDecimal,
      BMWtchctr_p_DynIpRstMax_C: BigDecimal,
      BMWtchctr_p_DynIpRstMin_C: BigDecimal,
      BMWtchctr_p_ReqDynIpStop_C: BigDecimal,
      BMWtchctr_pct_WgIpLimMax_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_pct_WgIpLimMin_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_pct_WgIpLimPlMin_C: BigDecimal,
      BMWtchctr_pct_WgIpMan_C: BigDecimal,
      BMWtchctr_pct_WgIpRstMax_C: BigDecimal,
      BMWtchctr_pct_WgIpRstMin_C: BigDecimal,
      BMWtchctr_pct_WgPosnIpStopMax_C: BigDecimal,
      BMWtchctr_pct_WgPosnIpStopMin_C: BigDecimal,
      BMWtchctr_pct_WgSpIpStopMax_C: BigDecimal,
      BMWtchctr_swi_IpFcdOn_C: String,
      BMWtchctr_swi_IpRstMan_C: String,
      BMWtchctr_swi_WgIpMan_C: String,
      BMWtchco_swi_FlGcCtlrOn_C: String,
      BMWtchctr_swi_IpPwrAcvn_C: String,
      BMWtchctr_b_IpRst_bo: OutMeasurement[BigDecimal],
      BMWtchctr_b_IpStop_bo: OutMeasurement[BigDecimal],
      BMWtchctr_fac_FadeAdp_ub: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgBefLim_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgIp_sw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgLimMax_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_Wg_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_Pos_10ms(
      BMWtchbas_b_FlGcHld_bo: BigDecimal,
      BMWtchbas_b_Noise_bo: BigDecimal,
      BMWtchbas_b_RaceStr_bo: BigDecimal,
      BMWtchbas_p_DifGra_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_AcvPl_bo: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_ClcPl_bo: BigDecimal,
      BMWtchco_b_Rdy_bo: BigDecimal,
      BMWtchco_fac_FadePl_ub: BigDecimal,
      BMWtchco_st_Opm_ub: BigDecimal,
      BMWtchctr_b_WgClsdPl_bo: BigDecimal,
      BMWtchctr_pct_WgBasc_uw: BigDecimal,
      Nkw: BigDecimal,
      Rf_soll: BigDecimal,
      BMWtchctr_fac_FilPctWgDyn_C: BigDecimal,
      BMWtchctr_fac_FilRatWg_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_p_DifGraWgClsd_C: BigDecimal,
      BMWtchctr_p_DifWgClsd_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_pct_WgClsdMin_C: BigDecimal,
      BMWtchctr_pct_WgClsdPl_C: BigDecimal,
      BMWtchctr_pct_WgDeltRaceStr_C: BigDecimal,
      BMWtchctr_pct_WgDyn_C: BigDecimal,
      BMWtchctr_pct_WgFlGc_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pct_WgNoise_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_pct_WgPlCond_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pct_WgPlEco_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pct_WgPlRoofOp_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pct_WgPlSpt_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pct_WgPl_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_ti_DlyPl_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_ti_DlyWgClsd_T: CurveType[BigDecimal, BigDecimal],
      BMWtchco_swi_FlGcCtlrOn_C: String,
      BMWtchctr_pct_WgCrtd1_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgCrtd3_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgRaw_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_Pwr2Pos_10ms(
      BMWbdy_b_EgFlp_bo: BigDecimal,
      BMWext_t_GasP2PclFilXab_sw: BigDecimal,
      BMWgpfp_b_PclFil_bo: BigDecimal,
      BMWgpfp_fac_AdpPclFil_uw: BigDecimal,
      BMWgpfp_m_SootLoad_sw: BigDecimal,
      BMWign_ag_OutMv_sw: BigDecimal,
      BMWtchbas_b_FlGc_bo: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_ClcCtlr_bo: BigDecimal,
      BMWtchco_st_Opm_ub: BigDecimal,
      BMWtchctr_pct_WgAltiCrtn_sw: BigDecimal,
      BMWtchctr_pct_WgRaw_uw: BigDecimal,
      BMWtchctr_pwr_Trb_uw: BigDecimal,
      BMWtchscv_fac__ub: BigDecimal,
      BMWtchsp_mf_Ex_uw: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      Eta_zyl_aus: BigDecimal,
      Msakzu: BigDecimal,
      Nkw: BigDecimal,
      Pumg: BigDecimal,
      Rf: BigDecimal,
      St_getrdaten: BigDecimal,
      St_getrdaten_B_gangwechsel_gs: BigDecimal,
      Tabg_mw: BigDecimal,
      Vsa_spri_f: BigDecimal,
      Zwstat: BigDecimal,
      BMWtchctr_cpp_ExGas_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_cw_FadeFlowSpSpt_C: BigDecimal,
      BMWtchctr_eff_CylOffMin_C: BigDecimal,
      BMWtchctr_fac_FadeFlowSpAcv_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_FadeFlowSpSpt_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_FadeTExGasGc_C: BigDecimal,
      BMWtchctr_fac_FadeTExGas_C: BigDecimal,
      BMWtchctr_fac_FadeTExGas_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_FilRatPTrb_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_TMdlCylOff_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_TrbEffIvs_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_TrbEffPlsCrtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_TrbExp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_gra_FadeTExGas_C: BigDecimal,
      BMWtchctr_pct_WgBasc_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_swi_ClcPwrWgPosn_C: String,
      BMWtchctr_t_EgCrtn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_t_ExGasFilMin_C: BigDecimal,
      BMWtchctr_t_ExGasMdlScav_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_t_ExGasMdl_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_t_MdlOfsIgRtd_T: CurveType[BigDecimal, BigDecimal],
      BMWausy_p_DifCat_T: CurveType[BigDecimal, BigDecimal],
      BMWausy_p_DifEgFlpClsd_T: CurveType[BigDecimal, BigDecimal],
      BMWausy_p_DifEgFlpOp_T: CurveType[BigDecimal, BigDecimal],
      BMWausy_p_DifPclFil_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWausy_swi_p_DifCatTot_C: String,
      KF_AUSY_TURB: MapType[BigDecimal, BigDecimal, BigDecimal],
      KL_FPKATREL_PUMG: CurveType[BigDecimal, BigDecimal],
      KL_TABG2TABG_WZINV: CurveType[BigDecimal, BigDecimal],
      K_ANZAHL_TURBOS: BigDecimal,
      BMWtchctr_pct_WgBasc_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_PwrFade_10ms(
      BMWtchbas_b_FlGcHld_bo: BigDecimal,
      BMWtchco_b_AcvPl_bo: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_ClcCtlr_bo: BigDecimal,
      BMWtchctr_pwr_Ctr_uw: BigDecimal,
      BMWtchctr_pwr_Pctl_uw: BigDecimal,
      BMWtchdiag_b_LimPctl_bo: BigDecimal,
      BMWtchsp_mf_CmprNorm_uw: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      BMWtchctr_fac_FilLimPctl_C: BigDecimal,
      BMWtchctr_fac_pwr_CompLimPctl_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_p_ReqDynLimPctl_C: BigDecimal,
      BMWtchctr_rat_p_ComprLimPctl_T: CurveType[BigDecimal, BigDecimal],
      BMWtchco_swi_FlGcCtlrOn_C: String,
      BMWtchctr_pwr_Trb_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchCtr_Pwr_10ms(
      BMWewgacp_pct_WgAvg_uw: BigDecimal,
      BMWtchad_fac_Raw_uw: BigDecimal,
      BMWtchbas_n_Dyn_sw: BigDecimal,
      BMWtchbas_p_BefCmpr_uw: BigDecimal,
      BMWtchbas_p_DifGra_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_ClcCtlr_bo: BigDecimal,
      BMWtchco_st_Opm_ub: BigDecimal,
      BMWtchctr_pct_WgBefLim_uw: BigDecimal,
      BMWtchctr_pct_WgLimMax_uw: BigDecimal,
      BMWtchctr_pct_Wg_uw: BigDecimal,
      BMWtchsp_fac_mf_CmprNorm_uw: BigDecimal,
      BMWtchsp_mf_CmprNorm_uw: BigDecimal,
      BMWtchsp_mf_Ex_uw: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      BMWtchtbc_fac_t_BefComp_uw: BigDecimal,
      Gangi_stat: BigDecimal,
      Nkw: BigDecimal,
      Var_at: BigDecimal,
      Var_dkg: BigDecimal,
      BMWtchco_cw_FadeDynSpt_C: BigDecimal,
      BMWtchctr_fac_DpDyn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_Dp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchctr_fac_FadeDynSpt_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_FadeDyn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_fac_FilFadeDyn_C: BigDecimal,
      BMWtchctr_fac_IpMax_C: BigDecimal,
      BMWtchctr_fac_IpMin_C: BigDecimal,
      BMWtchctr_fac_IpRstMax_C: BigDecimal,
      BMWtchctr_fac_IpRstMin_C: BigDecimal,
      BMWtchctr_fac_Ip_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_n_DynIpRstMax2_C: BigDecimal,
      BMWtchctr_n_DynIpRstMin2_C: BigDecimal,
      BMWtchctr_n_PpLimMax_C: BigDecimal,
      BMWtchctr_n_PpLimMin_C: BigDecimal,
      BMWtchctr_p_DifCrtnPpDyn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_p_DifCrtnPp_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_p_DifGraPpLimOff_C: BigDecimal,
      BMWtchctr_p_DifIpRstMax2_C: BigDecimal,
      BMWtchctr_p_DifIpRstMin2_C: BigDecimal,
      BMWtchctr_p_DifPpLimOff_C: BigDecimal,
      BMWtchctr_p_DynIpRstMax2_C: BigDecimal,
      BMWtchctr_p_DynIpRstMin2_C: BigDecimal,
      BMWtchctr_pct_WgPosnIpStopMax2_C: BigDecimal,
      BMWtchctr_pct_WgPosnIpStopMin2_C: BigDecimal,
      BMWtchctr_pct_WgSpIpStopMax2_C: BigDecimal,
      BMWtchctr_pwr_CmprGra_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pwr_Dp_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_pwr_Pctl_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchctr_rat_p_CmprPpLimMax_C: BigDecimal,
      BMWtchctr_rat_p_CmprPpLimMin_C: BigDecimal,
      BMWtchctr_swi_IpPwrAcvn_C: String,
      BMWtchctr_swi_IpRstMan2_C: String,
      BMWtchctr_ti_DlyPpLimOff_C: BigDecimal,
      BMWtchctr_ti_ToutPpLim_C: BigDecimal,
      BMWtchctr_b_IpRst2_bo: OutMeasurement[BigDecimal],
      BMWtchctr_b_IpStop2_bo: OutMeasurement[BigDecimal],
      BMWtchctr_fac_Ip_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pct_WgAct_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pwr_Ctr_uw: OutMeasurement[BigDecimal],
      BMWtchctr_pwr_Pctl_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchDiag_10ms(
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWewgacp_posn__sw: BigDecimal,
      BMWewgsp_posn__sw: BigDecimal,
      Nkw: BigDecimal,
      Pssol: BigDecimal,
      Rf_soll: BigDecimal,
      BMWtchdiag_fac_FilPPreThr_C: BigDecimal,
      BMWtchdiag_p_MnfSp_C: BigDecimal,
      BMWtchdiag_p_PreThrDynMin_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_p_PreThrPlau_C: BigDecimal,
      BMWtchdiag_p_PreThrPlau_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_posn_Dif10Milli_C: BigDecimal,
      BMWtchdiag_posn_DifThd_C: BigDecimal,
      BMWtchdiag_posn_WgMax_C: BigDecimal,
      BMWtchdiag_rf_MaxPBefThrHiInc_C: BigDecimal,
      BMWtchdiag_rf_MaxPBefThrHi_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_rf_Min_C: BigDecimal,
      BMWtchdiag_ti_DlyPBefThrHi2_C: BigDecimal,
      BMWtchdiag_ti_DlyPBefThrHi_C: BigDecimal,
      BMWtchdiag_b_PBefThrHi_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_rf_MaxPBefThrHi_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchDiag_Co_100ms(
      BMWeisy_b_PSnsrDblErr_bo: BigDecimal,
      BMWeisy_b_PSnsrPreThrErr_bo: BigDecimal,
      BMWemm_ct_StDrv_ub: BigDecimal,
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWtchdiag_swi_FidNew_C: String,
      BMWtchdiag_swi_Rst_C: String,
      BMWtchdiag_b_AdpOff_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_CtlrOff_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_DiagOff_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_LimPctl_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_rf_Lim_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_tq_Lim_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchDiag_Obd_100ms(
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchdiag_b_Acv_bo: BigDecimal,
      Pumg: BigDecimal,
      BMWtchdiag_ti_DlyDiagCmpl_C: BigDecimal,
      BMWtchdiag_b_RbmDen_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_RbmNum_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchDiag_P_100ms(
      BMWtchbas_b_RaceStr_bo: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchbas_p_TcBasc_uw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchctr_pct_WgBefLim_uw: BigDecimal,
      BMWtchctr_pct_WgCrtd3_uw: BigDecimal,
      BMWtchctr_pwr_Pctl_uw: BigDecimal,
      BMWtchctr_pwr_Trb_uw: BigDecimal,
      BMWtchdiag_b_DiagOff_bo: BigDecimal,
      BMWtchdiag_b_PBefThrHi_bo: BigDecimal,
      BMWtchsp_p_Req_uw: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      BMWtchtbc_t_BefCmprMnfAvg_sw: BigDecimal,
      Eta_zyl_aus: BigDecimal,
      Mshfm_kor: BigDecimal,
      Mszyl_diag: BigDecimal,
      Nkw: BigDecimal,
      Pumg: BigDecimal,
      Rf_soll: BigDecimal,
      BMWtchdiag_fac_FilRatAirFlow_C: BigDecimal,
      BMWtchdiag_n_EngMax_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_n_EngMin_C: BigDecimal,
      BMWtchdiag_p_OfsDiagOn_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_pct_WgPHi_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchdiag_pct_WgPLo_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchdiag_rat_mf_NotOkMin_C: BigDecimal,
      BMWtchdiag_rat_mf_OkMax_C: BigDecimal,
      BMWtchdiag_rat_mf_OkMin_C: BigDecimal,
      BMWtchdiag_rat_p_CmprMax_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_rat_p_CmprMin_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchdiag_rf_SpMin_C: BigDecimal,
      BMWtchdiag_swi_PBefThrHiFis_C: String,
      BMWtchdiag_ti_DebPLo_C: BigDecimal,
      BMWtchdiag_ti_DlyHiLo_T: CurveType[BigDecimal, BigDecimal],
      BMWtchdiag_b_Acv_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_PHi_bo: OutMeasurement[BigDecimal],
      BMWtchdiag_b_PLo_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchOb_Co_10ms(
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWtchbas_p_DifGra_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec2_bo: BigDecimal,
      BMWtchob_b_Trig_bo: BigDecimal,
      BMWtchob_tq_Delt_sw: BigDecimal,
      Nkw: BigDecimal,
      BMWtchob_p_DifEnd2_C: BigDecimal,
      BMWtchob_p_DifEnd_C: BigDecimal,
      BMWtchob_p_DifGraEnd_C: BigDecimal,
      BMWtchob_ti_HldChgSp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchob_ti_Hld_C: BigDecimal,
      BMWtchob_ti_Max_T: CurveType[BigDecimal, BigDecimal],
      BMWtchob_b_HldChgSp_bo: OutMeasurement[BigDecimal],
      BMWtchob_st_Opm_ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchOb_Tq_10ms(
      BMWtchco_b_Clc10MilliSec2_bo: BigDecimal,
      BMWtchob_st_Opm_ub: BigDecimal,
      Gangi_stat: BigDecimal,
      Nkw: BigDecimal,
      St_egsprog_kor: BigDecimal,
      St_progression: BigDecimal,
      St_progression_B_eco: BigDecimal,
      St_progression_B_sport: BigDecimal,
      Tans: BigDecimal,
      Var_dkg: BigDecimal,
      Var_hs: BigDecimal,
      BMWtchob_cw_AtEna_T: CurveType[String, BigDecimal],
      BMWtchob_cw_DctEna_T: CurveType[String, BigDecimal],
      BMWtchob_cw_MtEna_C: BigDecimal,
      BMWtchob_cw_MtSptEna_C: BigDecimal,
      BMWtchob_fac_tq_Delt_T: CurveType[BigDecimal, BigDecimal],
      BMWtchob_swi_DeacEco_C: String,
      BMWtchob_tq_Dec_C: BigDecimal,
      BMWtchob_tq_Delt_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchob_tq_Delt_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchOb_Trig_10ms(
      BMWtchbas_p_DifGra_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Clc10MilliSec2_bo: BigDecimal,
      BMWtchdiag_b_rf_Lim_bo: BigDecimal,
      BMWtchdiag_b_tq_Lim_bo: BigDecimal,
      Gangi_stat: BigDecimal,
      Mdk_wunsch: BigDecimal,
      Mdk_wunsch_grad: BigDecimal,
      Pwg_ist: BigDecimal,
      St_as_plaus: BigDecimal,
      St_as_plaus_B_anhang_plaus: BigDecimal,
      St_as_plaus_B_csn_egs_plaus: BigDecimal,
      St_as_plaus_B_egs_khl1_plaus: BigDecimal,
      St_as_plaus_B_egs_khl2_plaus: BigDecimal,
      St_as_plaus_B_fagurt_plaus: BigDecimal,
      St_as_plaus_B_fg_overboost_em2_plaus: BigDecimal,
      St_as_plaus_B_fg_rennstart_gb1_plaus: BigDecimal,
      St_as_plaus_B_ftauf1_plaus: BigDecimal,
      St_as_plaus_B_gangwechsel_gs_plaus: BigDecimal,
      St_as_plaus_B_hkauf_plaus: BigDecimal,
      St_as_plaus_B_hz_plaus: BigDecimal,
      St_as_plaus_B_kl15_ep_plaus: BigDecimal,
      St_as_plaus_B_kupp1_plaus: BigDecimal,
      St_as_plaus_B_mhauf1_plaus: BigDecimal,
      St_as_plaus_B_schlok_plaus: BigDecimal,
      St_as_plaus_B_sochold_anf_plaus: BigDecimal,
      St_egsprog_kor: BigDecimal,
      St_mdinfo_s: BigDecimal,
      St_shift: BigDecimal,
      Tmot: BigDecimal,
      Var_hs: BigDecimal,
      BMWtchob_cw_GcUpDwnAtTrig_C: BigDecimal,
      BMWtchob_cw_GearAtTrig_T: CurveType[String, BigDecimal],
      BMWtchob_cw_GearMtTrig_C: BigDecimal,
      BMWtchob_cw_TqInfoAtTrig_C: BigDecimal,
      BMWtchob_p_DifGraTrigMin_C: BigDecimal,
      BMWtchob_p_DifTrigMin_C: BigDecimal,
      BMWtchob_rat_AccrAtTrigMin_C: BigDecimal,
      BMWtchob_rat_AccrMtTrigMin_C: BigDecimal,
      BMWtchob_t_EngMin_C: BigDecimal,
      BMWtchob_tq_GraTrigMin_C: BigDecimal,
      BMWtchob_tq_TrigMin_C: BigDecimal,
      BMWtchob_b_Trig_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchOut_10ms(
      BMWeisy_b_DiagAirFlowCoaEnd_bo: BigDecimal,
      BMWeng_b_CkMovg_bo: BigDecimal,
      BMWeng_b_StrEnd_bo: BigDecimal,
      BMWlhmplau_b_StrSysAcv_bo: BigDecimal,
      BMWtchbas_b_Noise_bo: BigDecimal,
      BMWtchbov_b_Acv_bo: BigDecimal,
      BMWtchco_b_Acv_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_b_CthIdl_bo: BigDecimal,
      BMWtchco_b_LnkAftCmprSlv_bo: BigDecimal,
      BMWtchco_b_Rdy_bo: BigDecimal,
      BMWtchctr_pct_Wg_uw: BigDecimal,
      BMWtchsp_mf_Ex_uw: BigDecimal,
      BMWtchsvc_b_Acv_bo: BigDecimal,
      BMWtchsvc_pct_Wg_uw: BigDecimal,
      BMWtqe_b_Dfco_bo: BigDecimal,
      Nkw: BigDecimal,
      St_as_in_fahrer2: BigDecimal,
      St_as_in_fahrer2_B_bls_fast: BigDecimal,
      St_as_in_fahrer2_B_bls_pred: BigDecimal,
      St_as_in_fahrer2_B_ll_fzg: BigDecimal,
      St_as_in_fahrer2_B_rennstart_as: BigDecimal,
      St_as_in_fahrer2_B_vl_fzg: BigDecimal,
      St_eisydiag_enahfmb_global: BigDecimal,
      St_eisydiag_enahfmb_global_B_eqpl_akt: BigDecimal,
      St_eisydiag_enahfmb_global_B_hfmplcd_akt: BigDecimal,
      St_eisydiag_enahfmb_global_B_hfmplll_akt: BigDecimal,
      BMWtchout_f_GasWg_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchout_pct_Dfco_C: BigDecimal,
      BMWtchout_pct_WgBlwOff_T: CurveType[BigDecimal, BigDecimal],
      BMWtchout_pct_WgCthIdl_C: BigDecimal,
      BMWtchout_pct_WgDfcoDiag_C: BigDecimal,
      BMWtchout_pct_WgMan_C: BigDecimal,
      BMWtchout_pct_WgNotRdy_C: BigDecimal,
      BMWtchout_pct_WgOfs_C: BigDecimal,
      BMWtchout_pct_WgStrt_C: BigDecimal,
      BMWtchout_pct_WgWait_C: BigDecimal,
      BMWtchout_swi_BlwOff_C: String,
      BMWtchout_swi_DfcoDiagWgOp_C: String,
      BMWtchout_swi_Dfco_C: String,
      BMWtchout_swi_PctWgMan_C: String,
      BMWtchout_ti_DlyDfcoDiagStr_C: BigDecimal,
      BMWtchout_f_GasWg_uw: OutMeasurement[BigDecimal],
      BMWtchout_pct_Wg_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchScv_Dyn_10ms(
      BMWext_t_GasInCatAvg_sw: BigDecimal,
      BMWtchbas_p_DifGra_sw: BigDecimal,
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchscv_b_Ena_bo: BigDecimal,
      BMWtchsp_p_ReqDyn_sw: BigDecimal,
      Fho: BigDecimal,
      Nkw: BigDecimal,
      Rfv_vns: BigDecimal,
      Tmot: BigDecimal,
      BMWtchscv_n_DynHysMax_C: BigDecimal,
      BMWtchscv_n_DynMax_C: BigDecimal,
      BMWtchscv_p_DifDynDeac_T: CurveType[BigDecimal, BigDecimal],
      BMWtchscv_p_DifMin_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_p_ReqDynMin_C: BigDecimal,
      BMWtchscv_rf_DynHysMin_C: BigDecimal,
      BMWtchscv_rf_DynMin_C: BigDecimal,
      BMWtchscv_swi_DynRstNotEna_C: String,
      BMWtchscv_t_EgCatRst_C: BigDecimal,
      BMWtchscv_t_EngMin_C: BigDecimal,
      BMWtchscv_t_ExGasCatMax_C: BigDecimal,
      BMWtchscv_ti_DlyDynDeac_T: CurveType[BigDecimal, BigDecimal],
      BMWtchscv_ti_DynLock_C: BigDecimal,
      BMWtchscv_ti_DynMax_T: CurveType[BigDecimal, BigDecimal],
      BMWtchscv_b_Dyn_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchScv_Ena_10ms(
      BMWign_ag_OutMv_sw: BigDecimal,
      BMWpim_b_PrevnScavProh_bo: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchscv_b_Wish_bo: BigDecimal,
      Bed_lamson_ok_xab: BigDecimal,
      F_basis: BigDecimal,
      Nkw: BigDecimal,
      Rf: BigDecimal,
      St_kr: BigDecimal,
      St_kr_B_krdws: BigDecimal,
      St_kr_B_krndy: BigDecimal,
      St_kr_B_warml_zykl: BigDecimal,
      Zwstat: BigDecimal,
      BMWtchscv_ag_IgRtd_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_VnsMax_C: BigDecimal,
      BMWtchscv_swi_KnkDetErrOff_C: String,
      BMWtchscv_ti_DebDeac_C: BigDecimal,
      K_ANZAHL_ABGBAENKE: BigDecimal,
      BMWtchscv_b_Ena_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchScv_Fac_10ms(
      BMWfcomain_cw_Perm_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchco_st_Opm_ub: BigDecimal,
      BMWtchscv_b_Dyn_bo: BigDecimal,
      BMWtchscv_b_Ena_bo: BigDecimal,
      Dla_wup: BigDecimal,
      Nkw: BigDecimal,
      Rfv_vns: BigDecimal,
      St_progression: BigDecimal,
      St_progression_B_eco: BigDecimal,
      St_progression_B_sport: BigDecimal,
      Tans: BigDecimal,
      Tmot: BigDecimal,
      BMWtchscv_fac_DynEco_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_Dyn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_GraDec_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_GraInc_C: BigDecimal,
      BMWtchscv_fac_ReqOff_C: BigDecimal,
      BMWtchscv_fac_ReqOn_C: BigDecimal,
      BMWtchscv_fac_StatEco_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_Stat_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_WupCrtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchscv_fac_Wup_T: CurveType[BigDecimal, BigDecimal],
      BMWtchscv_swi_ReqMan_C: String,
      BMWtchscv_swi_StatEcoInh_C: String,
      BMWtchscv_b_Req_bo: OutMeasurement[BigDecimal],
      BMWtchscv_b_Wish_bo: OutMeasurement[BigDecimal],
      BMWtchscv_fac_Acv_ub: OutMeasurement[BigDecimal],
      BMWtchscv_fac__ub: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchSp_P_10ms(
      BMWeisy_b_PSnsrPreThrPlau_bo: BigDecimal,
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWgpfdiag_rf_LimPclFil_sw: BigDecimal,
      BMWgpfp_b_PclFil_bo: BigDecimal,
      BMWtchbas_b_RaceStr_bo: BigDecimal,
      BMWtchbas_p_BefCmpr_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchdiag_b_rf_Lim_bo: BigDecimal,
      BMWtchdiag_b_tq_Lim_bo: BigDecimal,
      BMWtchdiag_rf_MaxPBefThrHi_sw: BigDecimal,
      BMWtchsp_mf_CmprNorm_uw: BigDecimal,
      BMWtchsp_volf_Ico_uw: BigDecimal,
      BMWtchtbc_t_BefCmpr_sw: BigDecimal,
      Drft_uk: BigDecimal,
      Fupsrf_kl: BigDecimal,
      Fupsrf_kor_f: BigDecimal,
      Nkw: BigDecimal,
      Pirg_kl: BigDecimal,
      Pirg_kor_f: BigDecimal,
      Pld_soll: BigDecimal,
      Pumg: BigDecimal,
      Rf_mdk_max: BigDecimal,
      Rf_vlsaug_max: BigDecimal,
      BMWtchsp_cw_1_C: BigDecimal,
      BMWtchsp_cw_RfLimAcv_C: BigDecimal,
      BMWtchsp_fac_FadeMdlFlLim_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchsp_fac_FilPDifReqMax_C: BigDecimal,
      BMWtchsp_fac_FilPDyn_C: BigDecimal,
      BMWtchsp_fac_FilPRatCmpr_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_fac_rf_MaxSmaMdl_C: BigDecimal,
      BMWtchsp_p_DifIco_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_p_OfsMaxHys_C: BigDecimal,
      BMWtchsp_p_OfsMax_C: BigDecimal,
      BMWtchsp_p_ReqMaxSnsrErr_C: BigDecimal,
      BMWtchsp_p_ReqMax_C: BigDecimal,
      BMWtchsp_rat_p_CmprMax_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchsp_rat_p_CmprPmp_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_rf_Liho_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_rf_LimThd_C: BigDecimal,
      BMWtchsp_swi_PSpRace_C: String,
      BMWtchsp_b_RfLimAcv_bo: OutMeasurement[BigDecimal],
      BMWtchsp_p_DifIco_uw: OutMeasurement[BigDecimal],
      BMWtchsp_p_ReqDyn_sw: OutMeasurement[BigDecimal],
      BMWtchsp_p_Req_uw: OutMeasurement[BigDecimal],
      BMWtchsp_rat_p_CmprLim_uw: OutMeasurement[BigDecimal],
      BMWtchsp_rat_p_Cmpr_uw: OutMeasurement[BigDecimal],
      Rf_max_pldmax: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchSp_Volf_10ms(
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWtchbas_p_BefCmpr_uw: BigDecimal,
      BMWtchbas_rat_p_BefCmpr_uw: BigDecimal,
      BMWtchco_b_Clc10MilliSec_bo: BigDecimal,
      BMWtchtbc_t_BefCmpr_sw: BigDecimal,
      Mk_kgh: BigDecimal,
      Mssol: BigDecimal,
      Pumg: BigDecimal,
      St_getrdaten: BigDecimal,
      St_getrdaten_B_gangwechsel_gs: BigDecimal,
      Tvdk: BigDecimal,
      BMWtchsp_fac_FadePBefTc_C: BigDecimal,
      BMWtchsp_fac_SqrtTBefTc_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_fac_mf_FilCmprNormGc_C: BigDecimal,
      BMWtchsp_fac_mf_FilCmprNorm_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsp_cw_1_C: BigDecimal,
      BMWtchsp_fac_mf_CmprNorm_uw: OutMeasurement[BigDecimal],
      BMWtchsp_mf_CmprNorm_uw: OutMeasurement[BigDecimal],
      BMWtchsp_mf_Ex_uw: OutMeasurement[BigDecimal],
      BMWtchsp_volf_BefTc_uw: OutMeasurement[BigDecimal],
      BMWtchsp_volf_Ico_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchSvc_Acv_100ms(
      BMWchas_st_OpmAcv_ub: BigDecimal,
      BMWeisy_p_PreThrPlau_uw: BigDecimal,
      BMWtchsvc_b_Ena_bo: BigDecimal,
      BMWtchsvc_b_Req_bo: BigDecimal,
      Md_reib_vm: BigDecimal,
      Mdi_opt_lam: BigDecimal,
      Mdkw_soll: BigDecimal,
      Nkw: BigDecimal,
      Pumg: BigDecimal,
      Tans: BigDecimal,
      Tumg: BigDecimal,
      BMWtchsvc_fac_FilP_C: BigDecimal,
      BMWtchsvc_fac_p_Crtn_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchsvc_lam_Req_C: BigDecimal,
      BMWtchsvc_n_IdlDec_C: BigDecimal,
      BMWtchsvc_n_IdlInc_C: BigDecimal,
      BMWtchsvc_n_IdlMax_C: BigDecimal,
      BMWtchsvc_n_IdlMin_C: BigDecimal,
      BMWtchsvc_n_Idl_C: BigDecimal,
      BMWtchsvc_p_DeltMin_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsvc_pct_WgOp_C: BigDecimal,
      BMWtchsvc_ti_CthAcvMax_C: BigDecimal,
      BMWtchsvc_ti_DebIdlNotOk_C: BigDecimal,
      BMWtchsvc_ti_DebPOk_C: BigDecimal,
      BMWtchsvc_ti_DebTqNotOk_C: BigDecimal,
      BMWtchsvc_ti_PChkMax_C: BigDecimal,
      BMWtchsvc_ti_TqMax_C: BigDecimal,
      BMWtchsvc_ti_n_IdlTot_C: BigDecimal,
      BMWtchsvc_tq_ResDec_C: BigDecimal,
      BMWtchsvc_tq_ResInc_C: BigDecimal,
      BMWtchsvc_tqi_AirTo_C: BigDecimal,
      BMWtchsvc_tqi_Air_T: CurveType[BigDecimal, BigDecimal],
      BMWtchsvc_b_Acv_bo: OutMeasurement[BigDecimal],
      BMWtchsvc_b_CthReq_bo: OutMeasurement[BigDecimal],
      BMWtchsvc_lam_Req_uw: OutMeasurement[BigDecimal],
      BMWtchsvc_n_Idl_sw: OutMeasurement[BigDecimal],
      BMWtchsvc_p_Delt_uw: OutMeasurement[BigDecimal],
      BMWtchsvc_pct_Wg_uw: OutMeasurement[BigDecimal],
      BMWtchsvc_st_Tstr_ub: OutMeasurement[BigDecimal],
      BMWtchsvc_tq_Res_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchSvc_Ena_100ms(
      BMWbdy_b_CluOp10_bo: BigDecimal,
      Gangi: BigDecimal,
      Pumg: BigDecimal,
      Pwg_ist: BigDecimal,
      St_atldiag2_in: BigDecimal,
      St_atldiag2_in_B_atlsvc_if: BigDecimal,
      St_getriebe: BigDecimal,
      St_getriebe_B_autget: BigDecimal,
      St_getriebe_B_dkgget: BigDecimal,
      St_llr_hyb: BigDecimal,
      St_llr_hyb_B_em1_max_xctl: BigDecimal,
      St_llr_hyb_B_em1_nctl_akt: BigDecimal,
      St_llr_hyb_B_em1_nctl_akt_k0zu: BigDecimal,
      St_llr_hyb_B_em1_nctl_akt_os: BigDecimal,
      St_mdllr_swi: BigDecimal,
      St_mdllr_swi_B_llr_on: BigDecimal,
      Tmot: BigDecimal,
      V: BigDecimal,
      BMWtchsvc_p_AmbMin_C: BigDecimal,
      BMWtchsvc_swi_Req_C: String,
      BMWtchsvc_t_EngMax_C: BigDecimal,
      BMWtchsvc_t_EngMin_C: BigDecimal,
      BMW_PT_TOP_PX_C: String,
      BMWtchsvc_b_Ena_bo: OutMeasurement[BigDecimal],
      BMWtchsvc_b_Req_bo: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchTbc_Co_100ms(
      BMWlhmplau_t_EnvUnf_sw: BigDecimal,
      BMWtchtbc_t_EngAmb_sw: BigDecimal,
      Msdk: BigDecimal,
      Ta_agd: BigDecimal,
      Tans: BigDecimal,
      Tumg: BigDecimal,
      BMWtchtbc_cw_t_BefCmpr_C: BigDecimal,
      BMWtchtbc_fac_FilFade_C: BigDecimal,
      BMWtchtbc_fac_t_Fade_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_swi_t_Amb_C: String,
      BMWtchtbc_t_BefCmprSub_C: BigDecimal,
      BMWtchtbc_t_Norm_C: BigDecimal,
      BMWtchtbc_fac_t_BefComp_uw: OutMeasurement[BigDecimal],
      BMWtchtbc_t_BefCmprMnfAvg_sw: OutMeasurement[BigDecimal],
      BMWtchtbc_t_BefCmpr_sw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchTbc_Mdl_100ms(
      BMWeng_b_CkMovg_bo: BigDecimal,
      BMWeng_b_StrEnd_bo: BigDecimal,
      Mszyl: BigDecimal,
      Nelueft_wm: BigDecimal,
      St_kl15: BigDecimal,
      St_kl15_B_dc_new: BigDecimal,
      St_kl15_B_kl15_ep: BigDecimal,
      St_kl15_B_kl15_vorab: BigDecimal,
      Tabg_mw: BigDecimal,
      Tmot: BigDecimal,
      Tn_abstell: BigDecimal,
      Tumg: BigDecimal,
      V_can: BigDecimal,
      BMWtchtbc_fac_EngHotIni_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_fac_EngHot_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchtbc_fac_FadeWoLoad_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_fac_FilFadeWoLoad_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_fac_FilTEx_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchtbc_fac_FilVVeh_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_fac_TExIni_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_fac_ti_EngStop_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_swi_EngAmbIniOld_C: String,
      BMWtchtbc_t_ExDifMax_C: BigDecimal,
      BMWtchtbc_t_ExDifMin_C: BigDecimal,
      BMWtchtbc_t_ExStat_T: CurveType[BigDecimal, BigDecimal],
      BMWtchtbc_ti_EngStopMax_C: BigDecimal,
      BMWtchtbc_v_Corr_M: MapType[BigDecimal, BigDecimal, BigDecimal],
      BMWtchtbc_fac_EngHot_ub: OutMeasurement[BigDecimal],
      BMWtchtbc_mair_Acv_uw: OutMeasurement[BigDecimal],
      BMWtchtbc_mair_Save_uw: OutMeasurement[BigDecimal],
      BMWtchtbc_t_EngAmbWiLoadSave_sw: OutMeasurement[BigDecimal],
      BMWtchtbc_t_EngAmb_sw: OutMeasurement[BigDecimal],
      BMWtchtbc_ti_EngStopSave_uw: OutMeasurement[BigDecimal],
      BMWtchtbc_v_VehEfc_uw: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchTbc_Mdl_swini(
      BMWeng_b_EcuPwsFaild_bo: BigDecimal,
      BMWtchtbc_mair_Save_uw: BigDecimal,
      BMWtchtbc_t_EngAmbWiLoadSave_sw: BigDecimal,
      BMWtchtbc_ti_EngStopSave_uw: BigDecimal
  ): Unit = {
    ???
  }

  def BMW_MOD_TchWrap_100ms(
      BMWtchdiag_b_Acv_bo: BigDecimal,
      BMWtchdiag_b_RbmDen_bo: BigDecimal,
      BMWtchdiag_b_RbmNum_bo: BigDecimal,
      BMWtchsvc_p_Delt_uw: BigDecimal,
      BMWtchsvc_st_Tstr_ub: BigDecimal,
      BMWtchtbc_mair_Acv_uw: BigDecimal,
      BMWtchtbc_mair_Save_uw: BigDecimal,
      BMWtchtbc_t_BefCmpr_sw: BigDecimal,
      BMWtchtbc_t_EngAmb_sw: BigDecimal,
      BMWtchtbc_v_VehEfc_uw: BigDecimal,
      Atlsvc_dpvdk1: OutMeasurement[BigDecimal],
      Mslui_lang: OutMeasurement[BigDecimal],
      Mslui_lang_nv: OutMeasurement[BigDecimal],
      St_atldiag_10ms: OutMeasurement[BigDecimal],
      St_atldiag_10ms_B_beratllek: OutMeasurement[BigDecimal],
      St_atldiag_rbm: OutMeasurement[BigDecimal],
      St_atldiag_rbm_B_atlr_denom: OutMeasurement[BigDecimal],
      St_atldiag_rbm_B_atlr_nom_b1: OutMeasurement[BigDecimal],
      St_atlsvc: OutMeasurement[BigDecimal],
      St_atlsvc_pvdk: OutMeasurement[BigDecimal],
      Tmotraum: OutMeasurement[BigDecimal],
      Tvldr: OutMeasurement[BigDecimal],
      V_tmotraum_kor: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchWrap_10ms(
      BMWtchbas_p_Dif_sw: BigDecimal,
      BMWtchbov_b_Acv_bo: BigDecimal,
      BMWtchbov_mf_ThrMin_uw: BigDecimal,
      BMWtchbov_mf_VvtMin_uw: BigDecimal,
      BMWtchob_tq_Delt_sw: BigDecimal,
      BMWtchout_f_GasWg_uw: BigDecimal,
      BMWtchout_pct_Wg_uw: BigDecimal,
      BMWtchscv_b_Req_bo: BigDecimal,
      BMWtchscv_fac__ub: BigDecimal,
      BMWtchsp_mf_Ex_uw: BigDecimal,
      BMWtchsp_rat_p_CmprLim_uw: BigDecimal,
      Dmd_over_boost: OutMeasurement[BigDecimal],
      F_atldyn: OutMeasurement[BigDecimal],
      F_pldsvld_f: OutMeasurement[BigDecimal],
      Mssol_akzu: OutMeasurement[BigDecimal],
      Mssolldk_ulv: OutMeasurement[BigDecimal],
      Mssollvt_ulv: OutMeasurement[BigDecimal],
      Pld_diff_xeb: OutMeasurement[BigDecimal],
      St_atlstat: OutMeasurement[BigDecimal],
      St_atlstat_B_atldyn: OutMeasurement[BigDecimal],
      Tvulv: OutMeasurement[BigDecimal],
      Tvwg: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }

  def BMW_MOD_TchWrap_swini(
      Atlsvc_dpvdk2: OutMeasurement[BigDecimal],
      Atlsvc_dpvdk3: OutMeasurement[BigDecimal]
  ): Unit = {
    ???
  }
}
